### ISSUE TITLE
Not working on OSX 10.11

### ISSUE THREAD

**Issue by alexmocanu** [uiucseclab/arpspoofdetect#1]
Hello, 

When I try to run this script I get these errors:

`WARNING: fileno: pcapy API does not permit to get capure file descriptor. Bugs ahead! Press Enter to trigger packet reading

Traceback (most recent call last):
  File "detect_arpspoof.py", line 97, in <module>
    sniff(filter = "arp", prn = packet_filter, store = 0)
  File "/usr/local/lib/python2.7/site-packages/scapy/sendrecv.py", line 586, in sniff
    p = s.recv(MTU)
  File "/usr/local/lib/python2.7/site-packages/scapy/arch/pcapdnet.py", line 145, in recv
    pkt = self.ins.next()
  File "/usr/local/lib/python2.7/site-packages/scapy/arch/pcapdnet.py", line 92, in next
    s,us = h.getts()
AttributeError: 'NoneType' object has no attribute 'getts'
WARNING: **del**: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.`

OSX 10.11.4
Python 2.7.11 (installed by default)
